name: airbyte_utils
version: '1.0'
config-version: 2
profile: normalize
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
target-path: ../build
log-path: ../logs
packages-install-path: /dbt
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: table
      airbyte_tables:
        +tags: normalized_tables
        +materialized: table
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
vars:
  dbt_utils_dispatch_list:
  - airbyte_utils
  json_column: _airbyte_data
  models_to_source:
    au_get_flat_file_all__1st_update_general_ab1: main._airbyte_raw_au_get_f__y_last_update_general
    au_get_flat_file_all__1st_update_general_ab2: main._airbyte_raw_au_get_f__y_last_update_general
    au_get_flat_file_all__1st_update_general_ab3: main._airbyte_raw_au_get_f__y_last_update_general
    au_get_flat_file_all___y_last_update_general: main._airbyte_raw_au_get_f__y_last_update_general
    au_orders_ab1: main._airbyte_raw_au_orders
    au_orders_ab2: main._airbyte_raw_au_orders
    au_orders_ab3: main._airbyte_raw_au_orders
    au_orders: main._airbyte_raw_au_orders
    au_get_sales_and_traffic_report_ab1: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traffic_report_ab2: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traffic_report_ab3: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traffic_report: main._airbyte_raw_au_get_sales_and_traffic_report
    au_listfinancialevents_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents: main._airbyte_raw_au_listfinancialevents
    au_orders_ordertotal_ab1: main._airbyte_raw_au_orders
    au_orders_ordertotal_ab2: main._airbyte_raw_au_orders
    au_orders_ordertotal_ab3: main._airbyte_raw_au_orders
    au_orders_ordertotal: main._airbyte_raw_au_orders
    au_get_sales_and_traf_2eport_salesbyasin_ab1: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traf_2eport_salesbyasin_ab2: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traf_2eport_salesbyasin_ab3: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traffic_report_salesbyasin: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traf_2ort_trafficbyasin_ab1: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traf_2ort_trafficbyasin_ab2: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traf_2ort_trafficbyasin_ab3: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traf___report_trafficbyasin: main._airbyte_raw_au_get_sales_and_traffic_report
    au_listfinancialevents_refundeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_refundeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_refundeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_refundeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_shipmenteventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_shipmenteventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_shipmenteventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_shipmenteventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2justmenteventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2justmenteventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2justmenteventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_adjustmenteventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2argebackeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2argebackeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2argebackeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_chargebackeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2rvicefeeeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2rvicefeeeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2rvicefeeeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_servicefeeeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2rochargeeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2rochargeeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2rochargeeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_retrochargeeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2recoveryeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2recoveryeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2recoveryeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevents_debtrecoveryeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2npaymenteventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2npaymenteventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2npaymenteventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__ouponpaymenteventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ervicingeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ervicingeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ervicingeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__oanservicingeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2thamazoneventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2thamazoneventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2thamazoneventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__aywithamazoneventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2shipmenteventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2shipmenteventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2shipmenteventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__rialshipmenteventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2uidationeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2uidationeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2uidationeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__aliquidationeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2teeclaimeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2teeclaimeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2teeclaimeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__aranteeclaimeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ntsettleeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ntsettleeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ntsettleeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__ipmentsettleeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2hholdingeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2hholdingeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2hholdingeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__xwithholdingeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__ovalshipmenteventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2spaymenteventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2spaymenteventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2spaymenteventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__ctadspaymenteventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2nsactioneventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2nsactioneventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2nsactioneventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__ltransactioneventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2lpaymenteventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2lpaymenteventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2lpaymenteventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__rdealpaymenteventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2vicesfeeeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2vicesfeeeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2vicesfeeeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__gservicesfeeeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ursementeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ursementeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ursementeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__eimbursementeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2yexpenseeventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2yexpenseeventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2yexpenseeventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__ilityexpenseeventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ercrediteventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ercrediteventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2ercrediteventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__ovidercrediteventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__ntadjustmenteventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2reversaleventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2reversaleventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2reversaleventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__ensereversaleventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__gtransactioneventlist: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2tpaymenteventlist_ab1: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2tpaymenteventlist_ab2: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent_2tpaymenteventlist_ab3: main._airbyte_raw_au_listfinancialevents
    au_listfinancialevent__lmentpaymenteventlist: main._airbyte_raw_au_listfinancialevents
    au_get_sales_and_traf_3deredproductsales_ab1: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traf_3deredproductsales_ab2: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traf_3deredproductsales_ab3: main._airbyte_raw_au_get_sales_and_traffic_report
    au_get_sales_and_traf__n_orderedproductsales: main._airbyte_raw_au_get_sales_and_traffic_report
